# Generated by Django 4.1.7 on 2023-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(verbose_name=models.CharField(max_length=255)),
        ),
    ]
