# Generated by Django 4.1.7 on 2023-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introce',
            field=models.CharField(max_length=155),
        ),
    ]
