# Generated by Django 4.1.7 on 2023-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_introce'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentend',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
